site_name: ELMSLN
pages:
- Home: index.md
- Install:
  - Installation: INSTALL.md
  - Learning Locker: lrs/LearningLocker.md
- End user guide:
  - Adding a course: enduser/add-a-course.md
  - Courses outline:
    - Editing content: enduser/courses/edit.md
    - Outline designer: enduser/courses/outline-designer.md
  - Media asset management:
    - Interactive H5P content: enduser/media/h5p.md
- Information architecture:
  - Index: ia/ia-index.md
  - System: ia/System.md
  - Roles: ia/User-Roles.md
  - Networked course data model: ia/Course-Model.md
  - Sections: ia/Sections.md
  - Tool architecture:
    - Online: systems/authority/online.md
    - Service vs. Authority: systems/service-vs-auth.md
    - What is an authority?: systems/authority.md
    - What is a service?: systems/service.md
- Description of network tools:
  - Authorities:
    - Media: systems/authority/media.md
    - Interact: systems/authority/interact.md
    - People: systems/authority/people.md
    - Inbox: systems/authority/inbox.md
    - LQ: systems/authority/lq.md
    - Grades: systems/authority/grades.md
  - Services:
    - Courses: systems/service/courses.md
    - Studio: systems/service/studio.md
    - Discuss: systems/service/discuss.md
    - Blog: systems/service/blog.md
    - Innovate: systems/developer/innovate.md
- Developer:
  - Contributing: development/contributing/Contributing.md
  - Roadmap: Roadmap.md
  - Process:
    - Concept development process: development/Concept-Process.md
    - Release cycle: development/Project-Release-Cycle.md
  - General questions:
    - Questions: development/Developer-questions.md
    - Should I upgrade modules?: development/Should-I-update-Drupal-modules.md
    - Where can I add modules / themes?: development/Where-can-I-add-new-modules-themes.md
    - Where should I point addresses?: development/Where-should-I-point-addresses.md
  - Structure:
    - Package structure: development/Package-Structure.md
    - Config directory: development/config-is-empty-what-do-I-put-there.md
    - Features specification: development/Features-Specification.md
  - Command line:
    - Command line: development/command-line.md
    - Drush examples: development/Drush-Targeting-Usage.md
    - How do I run upgrades?: development/upgrades/How-do-I-run-upgrades.md
    - Legacy MOOC upgrade: development/upgrades/Course-UX-upgrade-for-0.1.0.md
  - General infrastructure:
    - Infrastructure: development/General-Infrastructure.md
    - Scale: development/scale.md
    - Vagrant: development/Vagrant-Step-by-Step-setup.md
  - Front end:
    - Style guide: development/front-end/Styleguide.md
    - Front end workflow: development/front-end/Front-End-Development-Workflow.md
  - Debug:
    - General debugging: development/debug.md
    - Reversing commits: development/Reverse-Commit-And-Push.md
    - Features builder: development/Features-Builder.md
    - Tool builder: development/Tool-Builder.md
- Acronyms: Acronyms.md
theme: readthedocs
site_author: "elmsln"
repo_name: ELMSLN
repo_url: https://github.com/elmsln/elmsln
